// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fnmb-logo/BoldHorizontal.tsx": () => import("../components/mockups/fnmb-logo/BoldHorizontal.tsx"),
  "./components/mockups/fnmb-logo/Current.tsx": () => import("../components/mockups/fnmb-logo/Current.tsx"),
  "./components/mockups/fnmb-logo/IconWordmark.tsx": () => import("../components/mockups/fnmb-logo/IconWordmark.tsx"),
  "./components/mockups/fnmb-logo/MarkFirst.tsx": () => import("../components/mockups/fnmb-logo/MarkFirst.tsx")
};
